### ISSUE TITLE
 DOMException: Failed to construct 'Worker': Script at '

### ISSUE THREAD

**Issue by JmingZhang** [Jack000/SVGnest#56]
i can run demo on the web site http://svgnest.com/.
however it reports errors when i download the file and run on the chrome version 60.
the error is shown in follow:
Any guidance would be appreciated. thank you 

![image](https://user-images.githubusercontent.com/11513241/31536446-380ee64e-b031-11e7-93b4-5711eb4e44df.png)

Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/eval.js' cannot be accessed from origin 'null'.
    at Parallel._spawnWorker (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/parallel.js:167:12)
    at Parallel._spawnMapWorker (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/parallel.js:217:24)
    at Parallel.p._spawnMapWorker (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/svgnest.js:351:47)
    at file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/parallel.js:265:10
    at Operation.then (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/parallel.js:51:5)
    at Parallel.map (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/util/parallel.js:263:18)
    at SvgNest.launchWorkers (file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/svgnest.js:354:6)
    at file:///C:/Users/Administrator/Desktop/fdm%20scheduling/SVGnest-master/SVGnest-master/svgnest.js:235:25
Parallel._spawnWorker @ parallel.js:167
Parallel._spawnMapWorker @ parallel.js:217
p._spawnMapWorker @ svgnest.js:351
(anonymous) @ parallel.js:265
Operation.then @ parallel.js:51
Parallel.map @ parallel.js:263
SvgNest.launchWorkers @ svgnest.js:354
(anonymous) @ svgnest.js:235

**Comment by JmingZhang** [comment]
this is a simple problem, the "js" files should be run in a web container (such as tomcat)
