### ISSUE TITLE
Unable to run after download

### ISSUE THREAD

**Issue by qggjonny** [Jack000/SVGnest#64]
It is a great work!I can run demo on the web site http://svgnest.com/. However it reports errors when i download the file and run on the chrome version 65. The error like this:
parallel.js:167 Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/temp/SVGnest-master/util/eval.js' cannot be accessed from origin 'null'.
    at Parallel._spawnWorker (file:///C:/temp/SVGnest-master/util/parallel.js:167:12)
    at Parallel._spawnMapWorker (file:///C:/temp/SVGnest-master/util/parallel.js:217:24)
    at Parallel.p._spawnMapWorker (file:///C:/temp/SVGnest-master/svgnest.js:351:47)
    at file:///C:/temp/SVGnest-master/util/parallel.js:265:10
    at Operation.then (file:///C:/temp/SVGnest-master/util/parallel.js:51:5)
    at Parallel.map (file:///C:/temp/SVGnest-master/util/parallel.js:263:18)
    at SvgNest.launchWorkers (file:///C:/temp/SVGnest-master/svgnest.js:354:6)
    at file:///C:/temp/SVGnest-master/svgnest.js:235:25
Thank you!

**Comment by bmtm** [comment]
web workers are needed to max out all cores on the cpu. unfortunately web workers don't work locally. if you need to run it locally I recommend installing an all in one server setup like wamp.

**Comment by qggjonny** [comment]
I run a SimpleHTTPServer on Python,It can run,Thank you!

**Comment by mc1893** [comment]
@qggjonny Can you show me how did setup/install everything on a pythons server? Or at least give me a starting point. Would appreciate it very much!
